#!/bin/bash
IP=192.168.1.201
if [ $# -ne 0 ]; then
	if [ $1 == "homer" ]; then
		IP=192.168.1.200
	fi
	if [ $1 == "margie" ]; then
		IP=192.168.1.201
	fi
fi
echo "setup module on $IP"
ssh root@${IP} 'rmmod hs1101lf; md5sum /lib/modules/4.4.16/hs1101lf.ko && rm /lib/modules/4.4.16/hs1101lf.ko'
/usr/bin/scp /wks/workspace/KernelModules/hs1101lf/hs1101lf.ko root@${IP}:/lib/modules/4.4.16/hs1101lf.ko
ssh root@${IP} 'md5sum /lib/modules/4.4.16/hs1101lf.ko && depmod -a'

# modprobe hs1101lf
